# Generated by Django 3.2.4 on 2026-10-02 01:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID da Categoria')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Categoria')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID do Usuário')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail do Usuário')),
                ('matricula', models.CharField(max_length=30, unique=True, verbose_name='Matrícula do Usuário')),
                ('tipo', models.CharField(choices=[('ALUNO', 'Aluno'), ('ADMIN', 'Administrador')], default='ALUNO', max_length=10, verbose_name='Tipo de Usuário')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Usuário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Usuário Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID do Livro')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('ano_publicacao', models.PositiveIntegerField(verbose_name='Ano de Publicação')),
                ('sinopse', models.TextField(blank=True, null=True, verbose_name='Sinopse')),
                ('arquivo_digital', models.FileField(blank=True, null=True, upload_to='livros/digitais/', verbose_name='Arquivo Digital (PDF/E-book)')),
                ('quantidade_disponivel', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Exemplares')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='arandu.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID do Empréstimo')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Empréstimo')),
                ('data_prevista_devolucao', models.DateField(verbose_name='Previsão de Devolução')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Devolvido em')),
                ('status', models.CharField(choices=[('ATIVO', 'Em Andamento'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado')], default='ATIVO', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='arandu.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='arandu.usuario', verbose_name='Aluno / Usuário')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
